# artifactory-cleanup.yaml
artifactory-cleanup:
  server: https://prashanttest.jfrog.io/artifactory
  user: $ARTIFACTORY_USERNAME
  password: $ARTIFACTORY_PASSWORD

  policies:
    - name: "Delete un-deployed artifacts after 30 days"
      rules:
        - rule: "lastDownloaded"
          olderThan: "30d"
        - rule: "neverDownloaded"
          value: "true"
      actions:
        - action: "deleteArtifacts"
      repository:
        include: ["*-dev-local"]
        exclude: ["*pro*"]

    - name: "Delete un-promoted build artifacts after 90 days"
      rules:
        - rule: "lastModified"
          olderThan: "90d"
      actions:
        - action: "deleteArtifacts"
      repository:
        include: ["*-build-local"]
        exclude: ["*pro*"]

    - name: "Preserve artifacts in 'pro' repositories"
      actions:
        - action: "preserve"
      repository:
        include: ["*pro*"]
