# artifactory-cleanup.yaml
artifactory-cleanup:
  server: https://prashanttest.jfrog.io/artifactory
  user: ${{ steps.setup-cli.outputs.oidc-user }}
  password: ${{ steps.setup-cli.outputs.oidc-token }}
  policies:
    - name: Conan - delete files older than 60 days
      rules:
        - rule: RepoByMask
          mask: "*testing*"
        - rule: PropertyNeq
          property_key: key-name
          property_value: 1
