name: Maven CI/CD

on: [push]
  #release:
   # types: [published]
permissions:
  id-token: write
  contents: read 
jobs:
  cleanup-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'  # Specify the Python version
    - name: Install artifactory-cleanup
      run: |
        python3 -mpip install artifactory-cleanup==1.0.0
    - name: Check installation
      run: artifactory-cleanup --help
      
