name: Maven CI/CD

on:  [push]
   #release:
    # types: [published]
permissions:
  id-token: write
  contents: write

jobs:
  versioning:
    uses: Pacificdubey/resuable-workflow/.github/workflows/artifact-destroy.yaml@main
    with:
      destroy: 'true'
      
