name: Upload Artifact

on: [ push ]
permissions:
  id-token: write
  contents: read 
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create JFrog Repository
        uses: Pacificdubey/resuable-workflow/.github/workflows/repo-creation.yml@main
        id: create_repo
