name: Upload Artifact

on: [ push ]
permissions:
  id-token: write
  contents: read 
jobs:
  create-repo:
     uses: Pacificdubey/resuable-workflow/.github/workflows/repo-creation.yml@main
     with:
          repo_type: maven
  upload-artifact:
    runs-on: ubuntu-latest
    needs: create-repo
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'adopt'
    - name: JFrog Setup
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4.2.2
      env:
        JF_URL: ${{ vars.JF_URL }} # This should be the base URL of your Artifactory
      with:
        oidc-provider-name: github
        oidc-audience: my-aud
    #- run: echo "${{ needs.create-repo.outputs.repo_name }}"
    - name: Build with Maven
      run: mvn clean package 
    - name: Upload to artifact
      run: |
        REPO_NAME="${{ needs.create-repo.outputs.repo_name }}"
        echo $REPO_NAME
        jfrog rt u "target/*.jar" "$REPO_NAME/"  --build-name="Resuable Workflow" --build-number="${{ github.run_number }}"
    - name: Publish Build Info
      run: |
          jfrog rt build-collect-env "Resuable Workflow" ${{ github.run_number }}
          jfrog rt bp "Resuable Workflow" ${{ github.run_number }}
          jfrog build-scan "Resuable Workflow" ${{ github.run_number }}

    






    
