name: Upload Artifact

on: [ push ]
permissions:
  id-token: write
  contents: read 
jobs:
  create-repo:
     uses: Pacificdubey/resuable-workflow/.github/workflows/repo-creation.yml@main

  upload-artifact:
    runs-on: ubuntu-latest
    needs: create-repo
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: echo "${{ needs.create-repo.outputs.repo_name }}"
