name: "Build and Deploy"

on: [ push]
  #  branches:
   #   - main

jobs:
  build:
    uses: your-organization/reusable-workflows/.github/workflows/new-way-semantic.yaml@main
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}

  artifact-upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
         repository: 'Pacificdubey/resuable-workflow'
         
        
      - name: Build Artifact
        run: |
          echo "Building artifact for version ${{ needs.build-and-upload.outputs.version }}"
          #
