name: "Build and Deploy"

on: [ push]
  #  branches:
   #   - mains
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  build:
    uses: Pacificdubey/resuable-workflow/.github/workflows/new-way-semantic.yaml@main
    secrets:
      custom_token: ${{ secrets.GITHUB_TOKEN }}

  artifact-upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build Artifact
        run: |
          echo "Building artifact for version ${{ needs.build-and-upload.outputs.version }}"
          #
