name: jFrog Docker Integration
on:
  push:
    branches:
      - main
env:
  RUN_NUMBER: ${{ github.run_number }}
permissions:
  id-token: write
  contents: read 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: JFrog Setup
        uses: jfrog/setup-jfrog-cli@v4.2.2
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: github
          oidc-audience: my-aud
      - name: Generate Docker authentication using OIDC token
        run: |
          export JFROG_TOKEN=$(jfrog rt curl -XPOST "/api/security/token" \
          --data '{
             "audience": "api://default",
             "grant_type": "client_credentials",
             "client_id": "GitHubActions"
              }' | jq -r '.access_token')
          echo $JFROG_TOKEN | docker login ${{ secrets.JFROG_URL }} --username _ --password-stdin

      - name: Build Docker image
        run: |
          docker images
          docker build -t pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER} .
      - name: Push Docker image to staging repository
        run: |
          docker push pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER}   









