name: jFrog Docker Integration
on:
  push:
    branches:
      - main
env:
  RUN_NUMBER: ${{ github.run_number }}
permissions:
  id-token: write
  contents: read 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: JFrog Setup
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4.2.2
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: github
          oidc-audience: my-aud
      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
         registry: ${{ secrets.JF_URL }}
         username: ${{ steps.setup-cli.outputs.oidc-user }}
         password: ${{ steps.setup-cli.outputs.oidc-token }}
      - name: Build Docker image
        run: |
          docker images
          docker build -t pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER} .
      - name: Push Docker image to staging repository
        run: |
          docker push pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER}  
      - name: Publish build info to JFrog
        run: |
          jfrog rt docker-push pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER} --build-name=my-docker-build --build-number=$RUN_NUMBER
          jfrog rt build-publish my-docker-build $RUN_NUMBER






