name: jFrog Docker Integration
on:
  push:
    branches:
      - main
env:
  RUN_NUMBER: ${{ github.run_number }}
permissions:
  id-token: write
  contents: read 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: JFrog Setup
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4.2.2
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: github
          oidc-audience: my-aud
      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
         registry: ${{ vars.JF_URL }}
         username: ${{ steps.setup-cli.outputs.oidc-user }}
         password: ${{ steps.setup-cli.outputs.oidc-token }}
      - name: Build Docker image
        run: |
          docker images
          docker build -t pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER} .
      - name: Push Docker image to staging repository
        run: |
         docker push pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER}  
     # - name: Publish build info to JFrog
       # run: |
        #  RUN_NUMBER=${{ github.run_number }}
         # IMAGE_TAG="pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER}"
          #TARGET_REPO="dockerkey-docker-dev-local"
          #jfrog  rt docker-push "$IMAGE_TAG" "$TARGET_REPO" --build-name=my-docker-build --build-number=$RUN_NUMBER
          #jfrog rt build-publish my-docker-build $RUN_NUMBER --project=dockerkey 
      - name: Get Docker image digest
        id: get-digest
        run: |
          IMAGE_TAG="pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER}"
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE_TAG" | cut -d '@' -f 2)
          echo "DIGEST=$DIGEST" >> $GITHUB_ENV
    # docker xray scanning   
      - name: docker scan
        run: |  
         jf docker pull pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER}
         jf docker scan pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER}
    # adding the built docker into the JFrog build info
      - name: add docker package to build
        run: |  
         echo "pacificdubey.jfrog.io/dockerkey-docker-dev-local/myapp:${RUN_NUMBER}@${{ env.DIGEST }}" > metadata.json
         jf rt build-docker-create dockerkey-docker-dev-local --image-file metadata.json

    # publishing and scanning a build info for the build
      - name: publish build info
        run: |
         jf rt build-collect-env my-docker-build ${{ github.run_number }}  --project=dockerkey  # Collect environment variables
         jf rt build-publish my-docker-build ${{ github.run_number }} --project=dockerkey    # Publish build info
         jf build-scan my-docker-build ${{ github.run_number }} --project=dockerkey






          






