name: jFrog Docker Integration
on:
  push:
    branches:
      - main
env:
  RUN_NUMBER: ${{ github.run_number }}
permissions:
  id-token: write
  contents: read 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: JFrog Setup
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4.2.2
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: github
          oidc-audience: my-aud
      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
         registry: ${{ vars.JF_URL }}
         username: ${{ steps.setup-cli.outputs.oidc-user }}
         password: ${{ steps.setup-cli.outputs.oidc-token }}









