name: Generic Upload

on: [push]
permissions:
  id-token: write
  contents: read 
jobs:
  create-repo:
     uses: Pacificdubey/resuable-workflow/.github/workflows/generic-repo.yaml@main

  upload-artifact:
    runs-on: ubuntu-latest
    needs: create-repo
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Sample ZIP
      run: |
          echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
          echo "VERSION=1.0.0" >> $GITHUB_ENV
          mkdir sample_code
          echo "print('Hello, JFrog!')" > sample_code/hello.py
          zip -r zip -r my-artifact_v${{ env.VERSION }}-${{env.TIMESTAMP}}.zip sample_code
    - name: JFrog Setup
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4.2.2
      env:
        JF_URL: ${{ vars.JF_URL }} # This should be the base URL of your Artifactory
      with:
        oidc-provider-name: github
        oidc-audience: my-aud
    - name: Upload to artifact
      run: |
        REPO_NAME="${{ needs.create-repo.outputs.repo_name }}"
        echo $REPO_NAME
        jfrog rt u "my-artifact_v${{ env.VERSION }}-${{TIMESTAMP}}.zip" "$REPO_NAME/sample_code/sample_code.zip" 
      env:
        JFROG_CLI_BUILD_NAME: Generic Python
    - name: Publish Build Info
      run: |
          jfrog rt build-collect-env
          jfrog rt bp 
          #jfrog build-scan
      env:
        JFROG_CLI_BUILD_NAME: Generic Python
