name: Generic Upload

on: [push]
permissions:
  id-token: write
  contents: read 
jobs:
  create-repo:
     uses: Pacificdubey/resuable-workflow/.github/workflows/generic-repo.yaml@main

  upload-artifact:
    runs-on: ubuntu-latest
    needs: create-repo
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set Timestamp and Version
      id: set-vars
      run: |
        echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        echo "VERSION=1.0.0" >> $GITHUB_ENV

    - name: Verify Environment Variables (Debugging Step)
      run: |
        echo "Timestamp: ${{ env.TIMESTAMP }}"
        echo "Version: ${{ env.VERSION }}"
    - name: Create Sample ZIP
      run: |
        mkdir sample_code
        echo "print('Hello, JFrog!')" > sample_code/hello.py
        zip -r "my-artifact_v${{ env.VERSION }}-${{ env.TIMESTAMP }}.zip" sample_code

    - name: List Files (Debugging Step)
      run: ls -la 

    - name: JFrog Setup
      id: setup-cli
      uses: jfrog/setup-jfrog-cli@v4.2.2
      env:
        JF_URL: ${{ vars.JF_URL }}
      with:
        oidc-provider-name: github
        oidc-audience: my-aud

    - name: Upload to Artifactory
      run: |
        REPO_NAME="${{ needs.create-repo.outputs.generic_repo }}"
        echo $REPO_NAME
        GIT_COMMIT="${{ github.sha }}"
        GIT_BRANCH="${{ github.ref_name }}"
        ARTIFACT_NAME="my-artifact_v${{ env.VERSION }}-${{ env.TIMESTAMP }}.zip"
        # Upload to Artifactory with properties
        jfrog rt u "$ARTIFACT_NAME" "$REPO_NAME/sample_code/" --target-props "git.commit=${GIT_COMMIT};git.branch=${GIT_BRANCH};build.timestamp=20240829064321"
      env:
        JFROG_CLI_BUILD_NAME: Generic Python
    - name: Publish Build Info
      run: |
          jfrog rt build-collect-env
          jfrog rt bp 
          #jfrog build-scan
      env:
        JFROG_CLI_BUILD_NAME: Generic Python
        
