name: Generic Upload

on: [push]
permissions:
  id-token: write
  contents: read 
jobs:
  create-repo:
     uses: Pacificdubey/resuable-workflow/.github/workflows/generic-repo.yaml@main

  upload-artifact:
    runs-on: ubuntu-latest
    needs: create-repo
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set Timestamp and Version
      id: set-vars
      run: |
        echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        echo "VERSION=1.0.0" >> $GITHUB_ENV

    - name: Verify Environment Variables (Debugging Step)
      run: |
        echo "Timestamp: ${{ env.TIMESTAMP }}"
        echo "Version: ${{ env.VERSION }}"
    - name: Create Sample ZIP
      run: |
        mkdir sample_code
        echo "print('Hello, JFrog!')" > sample_code/hello.py
        zip -r "my-artifact_v${{ env.VERSION }}-${{ env.TIMESTAMP }}.zip" sample_code

    - name: List Files (Debugging Step)
      run: ls -la 
