name: Generic Upload

on: [push]
   #release:
   #  types: [published]
permissions:
  id-token: write
  contents: write
env:
  BUILD_NUMBER: ${{ github.run_number }}
  VERSION: ${{ needs.versioning.outputs.new_version }}
jobs:
  versioning:
    uses: Pacificdubey/resuable-workflow/.github/workflows/semantic-version.yml@main
    with:
      version_file_path: './version.txt'
      patch: true  # Or change this based on release type or other logic
  create-repo:
     uses: Pacificdubey/resuable-workflow/.github/workflows/generic-repo.yaml@main

  upload-artifact:
    runs-on: ubuntu-latest
    needs: [create-repo, versioning]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set Version
      id: set-vars
      run: |
        echo "Version: ${{ env.VERSION }}"
    - name: Create Sample ZIP
      run: |
        mkdir sample_code
        echo "print('Hello, JFrog!')" > sample_code/hello.py
        zip -r "my-artifact_${{ env.VERSION }}-${{ env.BUILD_NUMBER }}.zip" sample_code
        ls -la
        
