name: Maven CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: JFrog Setup
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4.2.2
        env:
          JF_URL: ${{ secrets.JF_URL }} # This should be the base URL of your Artifactory
        with:
          oidc-provider-name: githubtest
          oidc-audience: aud

      - name: Build with Maven
        run: mvn clean install
      - name: JFrog Maven Config
        run: |
         jfrog rt mvn-config \
         --repo-deploy-releases=maventest-libs-release-local \
         --repo-deploy-snapshots=maventest-libs-snapshot-local

      - name: Publish to JFrog Artifactory
        run: |
           jfrog rt mvn deploy \
            --build-name="Maven CI/CD" \
            --build-number=${{ github.run_number }}
      - name: Xray Scan and Publish Build Info
        run: |
         # Collect and publish the build info
         jfrog rt build-collect-env "Maven CI/CD" ${{ github.run_number }}
         jfrog rt build-publish "Maven CI/CD" ${{ github.run_number }}
