name: JFrog Integration with Github Actions
on: [push]
  # release:
    # types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Repsoitory checkout
       uses: actions/checkout@v4
     - name: Python Setup
       uses: actions/setup-python@v4
       with:
         python-version: '3.9'
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         python -m pip install build
         pip install -r requirements.txt
     - name: Build release distributions
       run: python -m build
     - name: upload build artifacts
       uses: actions/upload-artifact@v4
       with:
        name: dist
        path: dist/

  deploy-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Download Build Artifcats
       uses: actions/download-artifact@v4
       with:
        name: dist
     - name: Setup JFrog CLI
       uses: jfrog/setup-jfrog-cli@v4
       with:
         version: '2.62.2'
       env:
         JF_PROJECT: "githubjfrog"
         JF_URL: ${{ secrets.JF_URL }}
         JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
         
     - name: Test Connection
       run: |
         # Ping the server
         jf rt ping
     - name: Upload artifact to staging
       run: ls -la    # jfrog rt upload "dist/*.whl" python-test-pypi-local/ -build-name=Staging --build-number=${{github.run_number}}
         
     

     








         
