name: JFrog Integration with Github Actions
on: [push]
  # release:
    # types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Repsoitory checkout
       uses: actions/checkout@v4
     - name: Python Setup
       uses: actions/setup-python@v4
       with:
         python-version: '3.9'
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         python -m pip install build
         pip install -r requirements.txt
     - name: Build release distributions
       run: python -m build
     - name: upload build artifacts
       run: ls -la
     








         
