name: Main Workflow

on: [push]
   #workflow_calls:

permissions:
    contents: write
    

jobs:
  versioning:
    uses: Pacificdubey/resuable-workflow/.github/workflows/final-semanting.yaml@main

  deploy:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Using Version
        run: |
         if [ "${{ needs.call-semantic-release.outputs.next_tag }}" = "v1.0.0" ]; then
          echo "No new release detected, using previous tag: ${{ needs.call-semantic-release.outputs.previous_tag }}"
          #echo "VERSION=${{ needs.call-semantic-release.outputs.previous_tag }}" >> $GITHUB_ENV
         else
          echo "New release detected, using next tag: ${{ needs.call-semantic-release.outputs.next_tag }}"
          #echo "VERSION=${{ needs.call-semantic-release.outputs.next_tag }}" >> $GITHUB_ENV
         fi
